import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#E3F2FD', padding: 20 },
  titulo: { fontSize: 20, fontWeight: 'bold', color: '#1565C0', marginBottom: 16, marginTop: 40 },
  vacio: { textAlign: 'center', color: '#1976D2', marginTop: 40, fontSize: 15 },
  tarjeta: { backgroundColor: '#fff', borderRadius: 12, padding: 16, marginBottom: 12, elevation: 3 },
  headerTarjeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  nombreEvento: { fontSize: 16, fontWeight: 'bold', color: '#1a1a2e', flex: 1, marginRight: 8 },
  infoEvento: { fontSize: 14, color: '#555', marginBottom: 2 },
  badgeInscrito: { backgroundColor: '#e3f2fd', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 3 },
  badgeAsistio: { backgroundColor: '#e8f5e9', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 3 },
  badgeTexto: { fontSize: 12, fontWeight: '600', color: '#1565C0' },
  botonAsistencia: { marginTop: 10, backgroundColor: '#4A90E2', padding: 10, borderRadius: 8, alignItems: 'center' },
  botonAsistenciaTexto: { color: '#fff', fontWeight: 'bold', fontSize: 13 },
  botonCancelar: { marginTop: 8, backgroundColor: '#ffe5e5', padding: 10, borderRadius: 8, alignItems: 'center' },
  botonCancelarTexto: { color: '#cc0000', fontWeight: 'bold', fontSize: 13 },
  modalFondo: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  modalCaja: { backgroundColor: '#fff', borderRadius: 16, padding: 24, width: '85%', elevation: 10 },
  modalTitulo: { fontSize: 18, fontWeight: 'bold', color: '#1a1a2e', marginBottom: 4 },
  modalSubtitulo: { fontSize: 14, color: '#555', marginBottom: 16 },
  modalInput: { borderWidth: 1, borderColor: '#ddd', borderRadius: 8, padding: 12, fontSize: 18, letterSpacing: 4, textAlign: 'center', marginBottom: 16 },
  modalBotonConfirmar: { backgroundColor: '#4A90E2', borderRadius: 8, padding: 14, alignItems: 'center', marginBottom: 10 },
  modalCancelar: { textAlign: 'center', color: '#888', fontSize: 14, paddingVertical: 4 },
  filtros: { flexDirection: 'row', marginBottom: 16, gap: 8 },
  filtroBton: { flex: 1, paddingVertical: 8, borderRadius: 20, backgroundColor: '#fff', alignItems: 'center', borderWidth: 1, borderColor: '#90CAF9' },
  filtroBtonActivo: { flex: 1, paddingVertical: 8, borderRadius: 20, backgroundColor: '#1565C0', alignItems: 'center' },
  filtroTexto: { fontSize: 13, color: '#1565C0', fontWeight: '600' },
  filtroTextoActivo: { fontSize: 13, color: '#fff', fontWeight: '600' },
  contadorTexto: { fontSize: 13, color: '#888', marginBottom: 10 },
});
